image: node:8.12.0

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@6.2.1
    - npm install
    - npm run build:prod
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
