image: node:8.12.0

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@6.2.1
    - npm install
    - ng build:prod
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
